### PR TITLE
Modify method of EPnP to static

### PR DESCRIPTION
**Pull request by ymd-stella**

### CODE REVIEW

**Comment by dimaxano** [comment]
Hello, @ymd-stella!
Can you please explain what was the motivation for implementing that feature?
Not arguing, just curious

**Comment by ymd-stella** [comment]
This is useful for including objects (or markers) of known 3D (or 2D) shape in the map.

**Comment by dimaxano** [comment]
Sorry, but still not clear
How making all methods static in that class helps with objects of known shape?

**Comment by ymd-stella** [comment]
We can use compute_pose without creating a pnp_solver object.

**Pull request merged**
