### PR TITLE
Modify license to GPLv3

### PR DESCRIPTION
**Pull request by ymd-stella**

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Woah woah, what? You can’t relicense someone elses work! Also GPL defies the entire point that OpenVSLAM was made for if you read their paper. It completely blocks companies like mine and most others from even considering to use this work

**Comment by SteveMacenski** [comment]
This is something I want to find a solution to because this license would completely block most ROS users, including myself, from even being able to file a ticket on this project (let alone use it in Nav2)

**Comment by mirellameelo** [comment]
@SteveMacenski I literally don't understand why they closed the open source project since they "did not observe any potential copyright infringement incidences". Honestly, I don't think they tell us the full history...

Well, now I'm super confused about what all of this means in practical effects. For example, my usage of OpenVSLAM has been to my dissertation. In this scenario, I could be affected as same as you with commercial intentions? Do you mind clarify about "[...] completely block most ROS users"? 

I'd appreciate follow-up on your interests in solving it, and also be useful as possible to help.

**Comment by SteveMacenski** [comment]
>  Honestly, I don't think they tell us the full history...

I think they are, it reads to me like their legal department said to remove the source from circulation. It's easier to just nuke it and walk away since they already got their publication out of it and weren't maintaining it anyhow. They did mention that this only came up from an internal review ("some internal concerns ") so it doesn't seem like anyone was actually making a problem about it externally / from ORB-SLAM people (lets be honest, GitHub is littered with mislicensed ORB-SLAM copies, they clearly don't care).

"we did not observe any potential copyright infringement incidences" -> even their internal review concluded that it was OK, but they're being hyper conservative. They then have a paragraph trying to shift liability, which is completely incorrect and untrue. Further, no one externally even made a problem about it so there shouldn't be a concern :shrug:. 

> Well, now I'm super confused about what all of this means in practical effects. 

In purely practical terms, anyone from any company basically cannot use this software anymore. I couldn't contribute, assist, or even file tickets on this project - nor could we use this to offer VSLAM integrations into the ROS2 ecosystem. 

> I could be affected as same as you with commercial intentions

Yes, you are also required to release all of your source code modifications with pretty strict versioning / changelog requirements. Anything you link against this work for must also be GPLv3 and made available to people who ask. 

* All of this is clearly with the understanding that I'm not a lawyer, just someone that deals with open source software alot

**Comment by ymd-stella** [comment]
Thank you for your comment.

The question of code similarity is a difficult one. I think we need to take a very hard look at whether OpenVSLAM can be written from the ORB_SLAM2 paper alone, without reading the ORB_SLAM2 code. Of course I am not a legal expert and the above is my personal view.

I think we should respect the fact that the original author stopped the release and recommended to use it under GPLv3. I have thought about what we can do to protect our rights regarding ORB_SLAM2 and OpenVSLAM. I think it would be good to clarify that the similarity between OpenVSLAM and ORB_SLAM2 is based on the ORB_SLAM2 paper. To do this, I think it would be a good idea to find similar codes and give comments that correspond to the descriptions in the ORB_SLAM2 papers. If we can make such an effort, we may consider continuing to publish under the BSD license.

**Comment by SteveMacenski** [comment]
I don't think that's necessary, but additional comments isn't a bad idea either. 

Either way, the relicensing though this PR proposes is technically illegal since you (nor I) have the right to blanket relicense other's work. Really, relicensing is actually at a complete impasse since the authors are not responsive, we would need every single one of their written permission to change the licensing for each commit in their contributions. Which is about [30 people](https://github.com/OpenVSLAM-Community/openvslam/graphs/contributors). 

> take a very hard look at whether OpenVSLAM can be written from the ORB_SLAM2 paper alone, without reading the ORB_SLAM2 code.

I believe it can be. I just did a bit of a glance around between the two and I really don't see enough similarities to make it seem that it has a problem in that regard. I can commit to spending a couple of hour and really diving into it, but I really think this is OK given AIST's position, the glancing I've done, and the paper's explanation of the implementation. 

> I think it would be good to clarify that the similarity between OpenVSLAM and ORB_SLAM2 is based on the ORB_SLAM2 paper

The [openvslam paper](https://arxiv.org/pdf/1910.01122.pdf) does this at length, its pretty well understood they employ similar techniques.

**Comment by jeremysalwen** [comment]
@SteveMacenski this issue is closed, but I think for the record it should be clear that it is *always* legal to re-license *any* BSD code as GPL.  That is one of the freedoms the BSD license gives you.

Obviously in this case the entire project is a derivative work of GPL code, so it would be *illegal* to offer it under any license other than the GPL, but I know that the maintainers of this project are in intense denial of that fact so there is no point in arguing about it further.

**Pull request closed without merging**
